import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../api/client";

const labels = {revenue:"Recognized revenue", direct_costs:"Direct variable delivery costs", cash:"Cash at month end", net_burn:"Net operating cash burn", paying_customers:"Paying customers", orders:"Completed orders", gmv:"Gross merchandise value"};
type MetricKey = keyof typeof labels;
type Month = { id:string; month:string; currency:string; source_note:string; field_sources?:Record<string,{source_name:string;quote?:string}> } & Partial<Record<MetricKey,string|number|null>>;
export type Metrics = {unresolved_calculations?:{name:string;reason:string;inputs:string[]}[];months:Month[]; calculations:{name:string;value:string;unit:string;formula:string;inputs:string[];explanation:string}[];note:string;latest_month:string|null;missing:string[]};
export type MetricImport = {id:string;source_name:string;status:string;issues:string[];record_ids?:string[]};
export default function CompanyMetrics({workspaceId,revision,metrics,imports=[],busy=false,onSaved}:{workspaceId:string;revision:number;metrics?:Metrics;imports?:MetricImport[];busy?:boolean;onSaved?:()=>void}) {
  const [sourceName,setSourceName]=useState("");
  const [sourceText,setSourceText]=useState("");
  const [values,setValues]=useState<Record<string,string>>({currency:"",month:"",source_note:""});
  const [editing,setEditing]=useState(false);
  const client=useQueryClient();
  const save=useMutation({mutationFn:()=>api.post(`/api/operations/workspaces/${workspaceId}/metrics`,{expected_revision:revision,update:{month:values.month,currency:values.currency,source_note:values.source_note,...Object.fromEntries(Object.keys(labels).map(k=>[k,values[k]?.trim() ? ['orders','paying_customers'].includes(k) ? Number(values[k]) : values[k] : null]))}}),onSuccess:()=>{setEditing(false);client.invalidateQueries({queryKey:["operations"]});onSaved?.();}});
  const read=useMutation({mutationFn:()=>api.post(`/api/operations/workspaces/${workspaceId}/metric-imports`,{expected_revision:revision,source_name:sourceName,text:sourceText}),onSuccess:()=>{setSourceText("");setSourceName("");client.invalidateQueries({queryKey:["operations"]});onSaved?.();}});
  const latestImport=imports.at(-1);
  const last=metrics?.months.at(-1);
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">Business performance</h2><p className="mt-2 text-sm text-slate-500">{last ? `${last.month} · ${last.currency} · company-reported` : "No dated operating figures yet. Product descriptions don't establish revenue or growth."}</p></div><button disabled={busy || read.isPending} onClick={()=>setEditing(!editing)} className="text-sm font-semibold text-indigo-600">{editing ? "Cancel" : "Enter figures manually"}</button></div>
    {last && <><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(labels).filter(([k])=>last[k as MetricKey]!==null && last[k as MetricKey]!==undefined).map(([k,label])=><div key={k} className="rounded-lg bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-lg font-semibold">{last[k as MetricKey]}</p></div>)}</div><p className="mt-3 text-xs text-slate-500">Source: {last.source_note}</p></>}
    {!!metrics?.calculations.length && <div className="mt-5 space-y-3">{metrics.calculations.map(c=><div key={c.name} className="rounded-lg border border-indigo-100 p-4"><div className="flex justify-between gap-3"><h3 className="text-sm font-semibold">{c.name}</h3><span className="font-semibold text-indigo-700">{c.value} {c.unit}</span></div><details className="mt-2 text-xs text-slate-500"><summary className="cursor-pointer">Calculation and source</summary><p className="mt-2">{c.formula}. {c.explanation}</p>{c.inputs.map(id=>{const r=metrics.months.find(m=>m.id===id);return <p key={id} className="mt-2">{r?.month}: {r?.source_note}</p>})}</details></div>)}</div>}
    {!!metrics?.unresolved_calculations?.length && <div className="mt-4 space-y-2 text-sm text-amber-800">{metrics.unresolved_calculations.map(c=><p key={c.name}>{c.name} needs clarification: {c.reason}</p>)}</div>}
    {!last && <p className="mt-4 max-w-3xl text-sm leading-6 text-slate-600">Add a dated founder or finance update to calculate revenue change, delivery contribution and cash coverage. Keep order value separate from company revenue. Leave unavailable figures blank.</p>}
    <form onSubmit={e=>{e.preventDefault();read.mutate();}} className="mt-5 space-y-3 border-t border-slate-100 pt-5">
      <h3 className="font-semibold">Let AI read the company update</h3><p className="text-sm leading-6 text-slate-500">Paste a dated founder or finance update. AI extracts supported monthly figures, then updates the current company analysis. Figures keep their source quotes; ambiguous items are flagged.</p>
      <label className="block text-sm font-medium">Update source<input required minLength={12} maxLength={300} value={sourceName} onChange={e=>setSourceName(e.target.value)} placeholder="Report name, author and date" className="mt-1 block w-full rounded-lg border border-slate-200 p-3" /></label>
      <label className="block text-sm font-medium">Company update<textarea required minLength={30} maxLength={18000} rows={5} value={sourceText} onChange={e=>setSourceText(e.target.value)} placeholder="Paste the original update, including its month, currency and metric definitions." className="mt-1 block w-full rounded-lg border border-slate-200 p-3" /></label>
      <button disabled={busy || read.isPending} className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{read.isPending ? "Submitting…" : busy ? "Company work in progress…" : "Read update & update analysis"}</button>
      {read.error && <p role="alert" className="text-sm text-rose-700">{read.error.message}</p>}
    </form>
    {latestImport && <div className="mt-4 rounded-lg bg-slate-50 p-4 text-sm"><p className="font-medium">{latestImport.source_name}</p><p className="mt-1 text-slate-600">{latestImport.status==='applied' ? `${latestImport.record_ids?.length || 0} monthly records saved. These figures will feed the company analysis.` : latestImport.status==='queued' ? "Update queued for AI extraction." : "This update needs attention."}</p>{!!latestImport.issues.length && <ul className="mt-2 list-disc space-y-1 pl-5 text-amber-800">{latestImport.issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul>}</div>}
    {last?.field_sources && <details className="mt-4 text-xs text-slate-500"><summary className="cursor-pointer">Quoted evidence for saved figures</summary>{Object.entries(last.field_sources).map(([key,source])=><p className="mt-3" key={key}><strong>{labels[key as MetricKey]}:</strong> {source.quote || "Manually supplied figure"} <span>— {source.source_name}</span></p>)}</details>}
    {editing && <form onSubmit={e=>{e.preventDefault();save.mutate();}} className="mt-5 space-y-4 border-t border-slate-100 pt-5"><p className="text-xs text-slate-500">Historical monthly totals only. Saving a correction replaces that month's active figures; earlier submissions remain in the record. Saving does not verify the source.</p><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-medium">Completed month<input required type="month" value={values.month} onChange={e=>setValues(v=>({...v,month:e.target.value}))} className="mt-1 block w-full rounded-lg border border-slate-200 p-2" /></label><label className="text-xs font-medium">Currency<input required pattern="[A-Z]{3}" maxLength={3} value={values.currency} onChange={e=>setValues(v=>({...v,currency:e.target.value.toUpperCase()}))} className="mt-1 block w-full rounded-lg border border-slate-200 p-2" /></label>{Object.entries(labels).map(([key,label])=><label key={key} className="text-xs font-medium">{label}<input type="number" min={key==='net_burn'?undefined:0} step={['orders','paying_customers'].includes(key)?'1':'any'} value={values[key]||''} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))} className="mt-1 block w-full rounded-lg border border-slate-200 p-2" placeholder="Unknown" /></label>)}</div><label className="block text-xs font-medium">Source and definition<textarea required minLength={12} value={values.source_note} onChange={e=>setValues(v=>({...v,source_note:e.target.value}))} className="mt-1 block w-full rounded-lg border border-slate-200 p-2" placeholder="Which report or founder update? Note the revenue/cost definitions. Cash burn excludes financing flows." /></label><button disabled={save.isPending} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{save.isPending?'Calculating…':'Save & calculate'}</button>{save.error && <p role="alert" className="text-sm text-rose-700">{save.error.message}</p>}</form>}
    {!!metrics?.months.length && <div className="mt-5 flex flex-wrap justify-between gap-3 text-xs text-slate-500"><p>{metrics.note}</p><a href={`/api/operations/workspaces/${workspaceId}/metrics`} className="font-semibold text-indigo-600">Download metrics ↓</a></div>}
  </section>;
}
