import {useState} from 'react';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {api} from '../api/client';
import CompanyMetrics from './CompanyMetrics';
import type {AnalystWorkspace} from './PreparationWorkspace';

type Finding={text:string;source_ids:string[]};
type Observation={id:string;metric:string;label:string;number_text:string;value:string;unit:string;period:string;qualification:string;meaning:string;quote:string;source_url:string};
type Need={id:string;kind:string;question:string;why:string;status:string;owner?:string};
export type CompanyAnalysisReport={last_completed_analysis?:CompanyAnalysisReport;status?:string;stale?:boolean;error?:string;issues?:string[];at?:string;
 retry_loop?:{status:string;max_passes:number;total_calls:number;elapsed_seconds:number;passes:{pass:number;status:string}[]};
 steps?:{at:string;phase:string}[];observations?:Observation[];sources?:{id:string;source_url:string;quote:string}[];
 answer?:{summary:Finding;findings:Finding[];outlook:{case:string;condition:string;implication:string;watch:string;source_ids:string[]}[]};
 needs?:Need[];source_outcomes?:{url:string;status:string;detail?:string}[];
 input_responses?:{question:string;note:string;at:string}[];
 scenarios?:{id:string;baseline:Observation;horizon_years:number;rationale:string;formula:string;values:{case:string;value:string;annual_growth_percent:string}[]}[]};

const panel='rounded-xl border border-slate-200 bg-white p-5 sm:p-6';
const button='rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50';
const input='mt-1 block w-full rounded-lg border border-slate-300 bg-white p-2 text-sm';

export default function CompanyAnalysis({workspace:w}:{workspace:AnalystWorkspace}){
 const task=w.company_analysis;const report=task?.answer?task:task?.last_completed_analysis||task;const client=useQueryClient();
 const busy=['queued','running'].includes(w.automation?.status||'');
 const [showInputs,setShowInputs]=useState(false);
 const [url,setUrl]=useState('');const [notes,setNotes]=useState<Record<string,string>>({});
 const [baseline,setBaseline]=useState('');const [years,setYears]=useState('1');
 const [rates,setRates]=useState({downside:'',base:'',upside:''});const [rationale,setRationale]=useState('');
 const refresh=()=>client.invalidateQueries({queryKey:['operations']});
 const run=useMutation({mutationFn:(body:{refresh?:boolean;public_urls?:string[];research_gaps?:boolean})=>api.post(`/api/operations/leads/${w.lead_id}/analysis-jobs`,body),onSuccess:refresh});
 const stop=useMutation({mutationFn:()=>api.post(`/api/operations/workspaces/${w.id}/preparation-jobs/${w.automation?.id}/stop`,{}),onSuccess:refresh});
 const reply=useMutation({mutationFn:(need:Need)=>api.post(`/api/operations/workspaces/${w.id}/analysis-inputs`,{expected_revision:w.revision,need_id:need.id,note:notes[need.id]}),onSuccess:refresh});
 const forecast=useMutation({mutationFn:()=>api.post(`/api/operations/workspaces/${w.id}/analysis-scenarios`,{expected_revision:w.revision,metric_id:baseline,horizon_years:Number(years),downside_growth:rates.downside,base_growth:rates.base,upside_growth:rates.upside,rationale}),onSuccess:refresh});
 const error=run.error||stop.error||reply.error||forecast.error;
 const unavailable=(report?.source_outcomes||[]).filter(s=>s.status!=='collected');
 const sourcePages=new Set(report?.sources?.map(s=>s.source_url)||[]).size;
 const humanNeeds=(report?.needs||[]).filter(n=>!['public_source','identity'].includes(n.kind));
 const publicNeeds=(report?.needs||[]).filter(n=>['public_source','identity'].includes(n.kind));
 const nextNeed=report===task?humanNeeds.find(n=>n.status!=='response_saved'):undefined;
 const baselines=[...(report?.observations||[]).filter(m=>['revenue','arr'].includes(m.metric)&&m.qualification==='reported'&&m.period&&m.unit!=='unknown').map(m=>({id:m.id,label:`${m.label} · ${m.number_text} ${m.unit} · ${m.period}`})),
  ...(w.metrics?.months||[]).filter(m=>m.revenue!==null&&m.revenue!==undefined).map(m=>({id:`local:${m.id}`,label:`Monthly revenue · ${m.revenue} ${m.currency} · ${m.month}`}))];
 const citations=(ids:string[])=><span className="mt-2 flex flex-wrap gap-3 text-xs text-indigo-600">{ids.map(id=>{const s=report?.sources?.find(s=>s.id===id);return s?<a key={id} href={s.source_url} target="_blank" rel="noreferrer">{new URL(s.source_url).hostname} ↗</a>:null;})}</span>;
 return <div className="space-y-5">
  <section className={panel}><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-base font-semibold">Company analysis</h3></div><button className={button} disabled={busy||run.isPending} onClick={()=>run.mutate({})}>{busy?'Working…':report?.answer?'Update analysis':report?.status?'Resume analysis':'Run company analysis'}</button></div>
   {task?.status&&<p className="mt-3 text-sm text-slate-600">{busy?w.automation?.phase:task.status==='waiting_for_input'?'Analysis available':task.status==='needs_review'?'The draft needs correction before it can be published.':task.status==='needs_attention'?'Analysis could not finish. Saved evidence is retained.':task.status.replaceAll('_',' ')}</p>}
   {busy&&<button className="mt-3 text-sm font-semibold text-rose-700" disabled={stop.isPending} onClick={()=>stop.mutate()}>Stop analysis</button>}
   {task?.retry_loop&&<p className="mt-2 text-xs text-slate-500">{task.retry_loop.passes.length} of {task.retry_loop.max_passes} passes finished · {task.retry_loop.total_calls} model calls · {Math.round(task.retry_loop.elapsed_seconds)} seconds total{task.retry_loop.status==='continuing'?' · Continuing saved corrections automatically.':task.retry_loop.status==='no_progress'?' · Paused because repeated attempts made no progress.':task.retry_loop.status==='pass_limit'?' · Correction limit reached; saved work can be resumed.':''}</p>}
   {report!==task&&<p className="mt-2 text-sm text-slate-600">Showing the last completed analysis while updated work is pending.</p>}{report?.stale&&<p className="mt-2 text-sm text-amber-800">Public evidence changed or expired. Update the analysis before relying on these findings.</p>}
   {error&&<p role="alert" className="mt-3 text-sm text-rose-700">{error.message}</p>}{task?.error&&<details className="mt-3 text-sm text-slate-500"><summary className="cursor-pointer">Why this attempt stopped</summary><p className="mt-2 whitespace-pre-wrap">{task.error}</p></details>}
   {!!task?.issues?.length&&<details className="mt-3 text-sm text-amber-800"><summary className="cursor-pointer">Review corrections to make</summary><ul className="mt-2 list-disc space-y-2 pl-5">{task.issues.map((i,n)=><li key={n}>{i}</li>)}</ul></details>}
   {!!task?.steps?.length&&<details className="mt-3 text-sm text-slate-500"><summary className="cursor-pointer">Workflow activity</summary><ol className="mt-2 list-decimal space-y-1 pl-5">{task.steps.map((s,i)=><li key={i}>{s.phase}</li>)}</ol></details>}
  </section>
  {report?.answer&&<section className={panel}><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">What the evidence tells us</h3><a className="text-sm font-semibold text-indigo-600" href={`/api/operations/workspaces/${w.id}/analysis-report`}>Download analysis & metrics ↓</a></div><p className="mt-3 text-sm leading-7 text-slate-700">{report.answer.summary.text}</p>{citations(report.answer.summary.source_ids)}{report.answer.findings.map((f,i)=><div className="mt-4 border-t border-slate-100 pt-4" key={i}><p className="text-sm leading-7 text-slate-700">{f.text}</p>{citations(f.source_ids)}</div>)}</section>}
  {report?.answer&&<section className={panel}><h3 className="font-semibold">Metrics found in public sources</h3><p className="mt-2 text-sm text-slate-500">Reported figures, targets and bounds retain their original meaning. They are not interchangeable.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{report.observations?.map(m=><article key={m.id} className="rounded-lg border border-slate-200 p-4"><p className="text-sm font-semibold">{m.label}</p><p className="mt-2 text-xl font-semibold">{m.number_text} <span className="text-sm font-normal">{m.unit==='unknown'?'currency/unit unspecified':m.unit}</span></p><p className="mt-1 text-xs text-slate-500">{m.qualification.replaceAll('_',' ')} · {m.period||'Reporting period not stated'}</p><p className="mt-3 text-sm leading-6 text-slate-600">{m.meaning}</p><details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer">Exact source passage</summary><blockquote className="mt-2 leading-6">{m.quote}</blockquote><a className="text-indigo-600" href={m.source_url} target="_blank" rel="noreferrer">Open source ↗</a></details></article>)}</div>{!report.observations?.length&&<p className="mt-3 text-sm text-slate-600">No numeric observations passed the source checks. Financial performance remains unestablished from the collected public evidence.</p>}</section>}
  {report?.answer&&<section className={panel}><h3 className="font-semibold">How the company could develop</h3><p className="mt-2 text-sm text-slate-500">Conditional outlooks, not predictions or assigned probabilities.</p><div className="mt-4 grid gap-4 lg:grid-cols-3">{report.answer.outlook.map(o=><article key={o.case} className="rounded-lg bg-slate-50 p-4"><h4 className="font-semibold capitalize">{o.case}</h4><p className="mt-3 text-sm leading-6">{o.condition}</p><p className="mt-3 text-sm leading-6 text-slate-700">{o.implication}</p><p className="mt-3 text-sm leading-6"><strong>Watch for: </strong>{o.watch}</p>{citations(o.source_ids)}</article>)}</div></section>}
  {!!w.metrics?.months?.length&&<CompanyMetrics workspaceId={w.id} revision={w.revision} metrics={w.metrics} imports={w.metric_imports} busy={busy} showInputs={false}/>}
  {!!publicNeeds.length&&<section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Public evidence still to establish</h3><button disabled={busy||run.isPending} onClick={()=>run.mutate({research_gaps:true})} className="text-sm font-semibold text-indigo-600 disabled:opacity-50">Research these gaps</button></div><p className="mt-2 text-sm leading-6 text-slate-500">These are research tasks for the system. You do not need to find the websites or filings.</p><details className="mt-3 text-sm text-slate-600"><summary className="cursor-pointer">See remaining checks ({publicNeeds.length})</summary>{publicNeeds.map(n=><div key={n.id} className="mt-3 border-t border-slate-100 pt-3"><p>{n.question}</p><p className="mt-1 text-xs text-slate-500">{n.why}</p></div>)}</details></section>}
  {report?.answer&&nextNeed&&<section className="rounded-xl border border-indigo-100 bg-indigo-50/50 p-5"><h3 className="font-semibold">Where your input would help</h3><p className="mt-3 text-sm font-medium leading-6">{nextNeed.question}</p><p className="mt-2 text-sm leading-6 text-slate-600">{nextNeed.why}</p><p className="mt-2 text-xs text-slate-500">The analysis above remains available. You can provide the original record; AI handles extraction and supported calculations.</p><button className="mt-3 text-sm font-semibold text-indigo-600" onClick={()=>setShowInputs(true)}>Add a company record</button><details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer">Record a response instead</summary><form className="mt-2 space-y-2" onSubmit={e=>{e.preventDefault();reply.mutate(nextNeed);}}><label>Your response<textarea required minLength={10} className={input} value={notes[nextNeed.id]||''} onChange={e=>setNotes({...notes,[nextNeed.id]:e.target.value})}/></label><button className={button} disabled={busy||reply.isPending}>Save response</button></form></details></section>}
  <details className={panel} open={showInputs} onToggle={e=>setShowInputs(e.currentTarget.open)}><summary className="cursor-pointer text-sm font-semibold">Add records or a source you already have (optional)</summary><p className="mt-3 text-sm leading-6 text-slate-500">Public research runs without these forms. Use this only to contribute information unavailable to the researcher.</p><div className="mt-4"><CompanyMetrics workspaceId={w.id} revision={w.revision} metrics={w.metrics} imports={w.metric_imports} busy={busy}/></div><details className="mt-4 text-sm"><summary className="cursor-pointer font-medium">Contribute a public source link</summary><form className="mt-3 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();run.mutate({public_urls:[url]});}}><label className="min-w-64 flex-1 text-xs">Public source URL<input type="url" required value={url} onChange={e=>setUrl(e.target.value)} className={input}/></label><button className={button} disabled={busy||run.isPending}>Read source & update analysis</button></form></details></details>
  {!!report?.source_outcomes?.length&&<details className={panel}><summary className="cursor-pointer text-sm text-slate-600">Research coverage · {sourcePages} source pages · {unavailable.length} requests unavailable</summary><p className="mt-3 text-sm text-slate-500">Inaccessible records remain unknown. A lookup is not a verified filing.</p><ul className="mt-3 space-y-2 text-sm">{report.source_outcomes.map((s,i)=><li key={i}><a href={s.url} target="_blank" rel="noreferrer" className="text-indigo-600">{new URL(s.url).hostname} ↗</a> · {s.status}{s.detail&&<p className="text-xs text-slate-500">{s.detail}</p>}</li>)}</ul><button className="mt-3 text-sm font-semibold text-indigo-600 disabled:opacity-50" disabled={busy||run.isPending} onClick={()=>run.mutate({refresh:true})}>Search for updated public records</button></details>}
  {report?.answer&&<details className={panel}><summary className="cursor-pointer text-sm font-semibold">Explore your own growth assumptions (optional)</summary><div className="mt-4"><p className="mt-2 text-sm text-slate-600">Choose a dated baseline and approve annual growth assumptions. The calculation keeps the baseline's metric and reporting period; it does not convert recurring revenue into earned revenue.</p>{baselines.length?<form onSubmit={e=>{e.preventDefault();forecast.mutate();}} className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Baseline<select className={input} required value={baseline} onChange={e=>setBaseline(e.target.value)}><option value="">Choose a supported figure</option>{baselines.map(b=><option key={b.id} value={b.id}>{b.label}</option>)}</select></label><label className="text-xs">Years after the baseline<input className={input} required type="number" min="1" max="5" value={years} onChange={e=>setYears(e.target.value)}/></label></div><div className="grid gap-3 sm:grid-cols-3">{(['downside','base','upside'] as const).map(k=><label className="text-xs capitalize" key={k}>{k} annual growth (%)<input required type="number" step="any" min="-100" max="200" className={input} value={rates[k]} onChange={e=>setRates({...rates,[k]:e.target.value})}/></label>)}</div><label className="block text-xs">Why these assumptions?<textarea required minLength={15} className={input} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><button className={button} disabled={busy||forecast.isPending||report.stale||report!==task}>Approve assumptions & calculate</button></form>:<p className="mt-3 text-sm text-amber-800">An exact, dated revenue baseline is missing. Add a completed month's company figures or an official source. A target or “approaching” value cannot be used as an exact baseline.</p>}{report.scenarios?.map(s=><div className="mt-5 border-t border-slate-200 pt-4" key={s.id}><p className="text-sm font-medium">{s.baseline.label} · {s.horizon_years} years after {s.baseline.period}</p><table className="mt-3 w-full text-left text-sm"><thead><tr><th>Scenario</th><th>Annual growth</th><th>Conditional value</th></tr></thead><tbody>{s.values.map(v=><tr key={v.case}><td className="py-2 capitalize">{v.case}</td><td>{v.annual_growth_percent}%</td><td>{Number(v.value).toLocaleString()} {s.baseline.unit}</td></tr>)}</tbody></table><p className="text-xs text-slate-500">{s.formula} · {s.rationale}</p></div>)}</div></details>}
 </div>;
}
