import {useMutation,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import type {Metrics} from './CompanyMetrics';
import {api} from '../api/client';
export type CaseProduct={measurement_formulas?:string[];measurements?:{population_basis:string;left:{record_needed:string};right:{record_needed:string}}[];review_state?:string;quality_review?:{issues:{category:string;excerpt:string;correction:string}[]};decision_question:string;next_action:string;completion_test:string;title:string;purpose:string;sections:{heading:string;content:string}[];missing_inputs:{record:string;why:string}[];evidence_ids:string[]};
export type InvestmentCaseData={stage_errors?:Record<string,string>;version:number;basis_hash:string;status:string;eligibility?:{maturity:string;evidence_ids:string[]};fit?:{maturity?:'early_business'|'established_business'|'unknown';decision:'proceed'|'clarify'|'do_not_pursue';company_type:string;rationale:string;next_action:string;evidence_ids:string[]};products?:Record<string,CaseProduct>};
export default function InvestmentCase({leadId,workspaceId,basis,data,busy,facts,metrics,onAddInputs}:{leadId:string;workspaceId?:string;basis?:string;data?:InvestmentCaseData;busy:boolean;metrics?:Metrics;onAddInputs?:()=>void;facts:{id:string;quote:string;source_url:string}[]}) {
 const client=useQueryClient();
 const prepare=useMutation({mutationFn:()=>api.post(`/api/operations/leads/${leadId}/readiness-jobs`),onSuccess:()=>client.invalidateQueries({queryKey:['operations']})});
 const current=data?.basis_hash===basis && data?.version===8;
 const fit=current?data?.fit:undefined;
 const savedDraftCount=current?Object.keys(data?.products||{}).length:0;
 const citations=(ids:string[])=> <details className="mt-4 text-sm text-slate-500"><summary className="cursor-pointer">Evidence behind this conclusion</summary>{facts.filter(f=>ids.includes(f.id)).map(f=><blockquote className="mt-3 border-l-2 border-indigo-100 pl-3" key={f.id}><p>{f.quote}</p><a className="mt-2 block text-indigo-600" href={f.source_url} target="_blank" rel="noreferrer">Read source ↗</a></blockquote>)}{metrics?.months.filter(m=>ids.includes(m.id)).map(m=><div key={m.id} className="mt-3"><p>{m.month} · {m.currency} · Company-reported figures</p><p className="mt-1">{m.source_note}</p>{Object.entries(m.field_sources||{}).map(([key,source])=><p className="mt-2" key={key}>{source.quote} — {source.source_name}</p>)}</div>)}</details>;
 return <div className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">Build the investment case</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">AI checks whether this engagement makes sense, then writes the decision memo, commercial validation document and investor narrative that the evidence supports.</p></div>{current && fit && workspaceId && <a href={`/api/operations/workspaces/${workspaceId}/investment-case`} className="text-sm font-semibold text-indigo-600">Download prepared work ↓</a>}</header>
 {current && !fit && data?.eligibility && <section className="rounded-2xl border border-indigo-100 bg-white p-7"><p className="text-xs font-semibold uppercase text-slate-500">Company stage · AI assessment</p><h3 className="mt-3 text-lg font-semibold">{data.eligibility.maturity === "established_business" ? "Established business" : data.eligibility.maturity === "early_business" ? "Early-stage business" : "Company stage needs clarification"}</h3><p className="mt-3 text-sm text-slate-600">The next step is to resolve whether this company fits the engagement before preparing investment materials.</p>{citations(data.eligibility.evidence_ids)}</section>}
 {!fit && !(current && data?.eligibility) && <section className="rounded-2xl border border-slate-200 bg-white p-7"><h3 className="font-semibold">Start with a decision, then produce the work</h3><p className="mt-3 text-sm leading-6 text-slate-600">No current preparation case has been produced. AI will assess this company against your objective before proposing incubation or fundraising. Unsupported conclusions will stay unknown.</p></section>}
 {fit && <section className={`rounded-2xl border p-7 ${fit.decision==='do_not_pursue'?'border-amber-200 bg-amber-50':'border-indigo-100 bg-white'}`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Engagement decision · AI assessment</p><h3 className="mt-3 text-xl font-semibold">{fit.decision==='do_not_pursue'?'Do not pursue this incubation engagement':fit.decision==='clarify'?'Resolve the engagement fit first':'Proceed with preparation'}</h3><p className="mt-3 text-sm font-medium">{fit.maturity === "established_business" ? "Established business" : fit.maturity === "early_business" ? "Early-stage business" : fit.maturity === "unknown" ? "Company stage needs clarification" : fit.company_type}</p><p className="mt-3 leading-7 text-slate-700">{fit.rationale}</p><div className="mt-5 border-t border-slate-200 pt-4"><h4 className="text-sm font-semibold">What happens next</h4><p className="mt-2 text-sm leading-6">{fit.next_action}</p></div>{fit.decision==='do_not_pursue' && <Link to="/leads" className="mt-5 inline-block rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Find matching companies →</Link>}{citations(fit.evidence_ids)}</section>}
 {current && !!Object.keys(data?.stage_errors||{}).length && <section className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><h3 className="font-semibold">{savedDraftCount?'Preparation is incomplete':'No preparation documents passed validation'}</h3><p className="mt-2">{savedDraftCount?`${savedDraftCount} working draft${savedDraftCount===1?' is':'s are'} available below, with any unresolved review questions.`:'Your company evidence and engagement assessment are saved.'} Finish preparation retries the unfinished documents using the same evidence.</p>{Object.entries(data?.stage_errors||{}).map(([stage,error])=><details className="mt-3" key={stage}><summary className="cursor-pointer">{stage.replaceAll('_',' ')} · correction needed</summary><p className="mt-2 text-slate-600">{error}</p></details>)}</section>}
 {current && data?.status==='needs_review' && <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Working drafts are available. Automated review questions remain unresolved; these materials are not verified for investor use.</p>}
 {current && Object.entries(data?.products||{}).map(([key,product],i)=><details key={key} open={i===0} className="rounded-2xl border border-slate-200 bg-white p-7"><summary className="cursor-pointer text-lg font-semibold">{product.title}</summary><p className="mt-3 text-sm text-slate-500">{product.purpose}</p><p className="mt-5 font-medium text-slate-800">{product.decision_question}</p>{product.sections.map((s,j)=><section className="mt-6" key={j}><h3 className="font-semibold">{s.heading}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{s.content}</p></section>)}{product.measurement_formulas?.map((formula,j)=><section key={j} className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><h3 className="font-semibold">Proposed measurement · results pending</h3><p className="mt-2">{formula}</p><p className="mt-2 text-slate-600">{product.measurements?.[j]?.population_basis}</p><p className="mt-2 text-slate-600">Records needed: {product.measurements?.[j]?.left.record_needed}; {product.measurements?.[j]?.right.record_needed}</p></section>)}{!!product.missing_inputs.length && <section className="mt-6 rounded-xl bg-amber-50 p-5"><h3 className="text-sm font-semibold">Company inputs needed to finish this work</h3>{product.missing_inputs.map((r,j)=><div className="mt-4" key={j}><p className="text-sm font-medium">{r.record}</p><p className="mt-1 text-sm leading-6 text-slate-600">{r.why}</p></div>)}</section>}<section className="mt-6 border-t border-slate-200 pt-5"><h3 className="text-sm font-semibold">Next action</h3><p className="mt-2 text-sm leading-6">{product.next_action}</p><h3 className="mt-4 text-sm font-semibold">What this work needs to establish</h3><p className="mt-2 text-sm leading-6 text-slate-600">{product.completion_test}</p></section>{!!product.quality_review?.issues.length && <details className="mt-5 text-sm text-amber-900"><summary className="cursor-pointer font-medium">Unresolved review questions · AI proposed</summary>{product.quality_review.issues.map((issue,j)=><p className="mt-3 leading-6" key={j}>{issue.correction}</p>)}</details>}{citations(product.evidence_ids)}</details>)}
 {(!current || data?.status!=='complete') && <button disabled={busy || prepare.isPending} onClick={()=>prepare.mutate()} className="rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy || prepare.isPending?'Preparing company work…':data?.status==='needs_review'?'Revise flagged drafts':fit?'Finish preparation work':'Prepare investment case'}</button>}
 {current && !!Object.values(data?.products||{}).flatMap(p=>p.missing_inputs).length && onAddInputs && <button onClick={onAddInputs} className="text-sm font-semibold text-indigo-600">Add a company update to develop this case →</button>}
 {prepare.error && <p role="alert" className="text-sm text-rose-700">{prepare.error.message}</p>}
 </div>
}
