import { useState } from "react";
import { Link, useOutletContext } from "react-router-dom";
import {
  useLeads,
  useReview,
  useDocuments,
} from "../../api/hooks";
import CitationDrawer from "../../components/CitationDrawer";
import StatTile from "../../components/StatTile";
import { formatFieldValue } from "../../lib/format";
import type {
  CimStructuredData,
  DocumentType,
  MemoVersion,
  ProformaStructuredData,
  TeaserStructuredData,
} from "../../api/types";

const TABS: { key: DocumentType; label: string }[] = [
  { key: "cim", label: "Investment memorandum" },
  { key: "teaser", label: "Anonymous introduction" },
  { key: "proforma", label: "Financial scenarios" },
];

export default function Documents() {
  const { dealId } = useOutletContext<{ dealId: string }>();
  const [activeTab, setActiveTab] = useState<DocumentType>("cim");
  const documents = useDocuments(dealId);
  const review = useReview(dealId);
  const leads = useLeads();
  const company = leads.data?.find(l=>l.promoted_deal_id === dealId);
  const [citationBlockId, setCitationBlockId] = useState<string | null>(null);

  if (documents.isLoading) return <p className="text-sm text-slate-500">Loading…</p>;
  if (documents.isError) return <section role="alert" className="rounded-xl border border-slate-200 bg-white p-6">
    <h1 className="text-xl font-semibold">Investor materials could not be loaded</h1>
    <p className="mt-3 text-sm text-slate-600">Try loading the saved documents again.</p>
    <button onClick={() => documents.refetch()} disabled={documents.isFetching} className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white disabled:opacity-50">{documents.isFetching ? "Loading…" : "Retry loading"}</button>
    <details className="mt-4 text-xs text-slate-500"><summary className="cursor-pointer">Error details</summary><p className="mt-2">{documents.error.message}</p></details>
  </section>;

  function latestOf(type: DocumentType): MemoVersion | undefined {
    return documents.data
      ?.filter((d) => d.document_type === type)
      .sort((a, b) => b.version_number - a.version_number)[0];
  }

  return (
    <div className="flex flex-col gap-4">
      <header className="rounded-xl border border-slate-200 bg-white p-6"><h1 className="text-xl font-semibold">Historical deal documents</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Documents below are saved legacy records, not validated investor materials. New introduction and pitch decks and an investment memorandum are generated by the local model in the deal room, with separate evidence, financial, semantic, export and release checks.</p>{company && <Link className="mt-4 inline-block text-sm font-semibold text-indigo-600" to={`/operations?lead=${company.id}&tab=readiness`}>Open deal room and current company work →</Link>}</header>
      <nav className="flex flex-wrap gap-1">
        {TABS.map((tab) => (
          <button
            key={tab.key}
            onClick={() => setActiveTab(tab.key)}
            className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors ${
              activeTab === tab.key ? "bg-indigo-600 text-white" : "bg-white text-slate-600 hover:bg-slate-100"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </nav>

      {!latestOf(activeTab) ? <section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-semibold">No saved historical {TABS.find(tab => tab.key === activeTab)?.label.toLowerCase()}</h2><p className="mt-3 text-sm leading-6 text-slate-600">The retired legacy compiler cannot create new files. Use the deal room for local-model drafts and current validation. Projection spreadsheets require a supplied model or explicitly requested generation with sufficient reviewed inputs.</p><div className="mt-5 flex flex-wrap gap-4">{company && <Link className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white" to={`/operations?lead=${company.id}&tab=readiness`}>Open deal room</Link>}<Link className="text-sm font-semibold text-indigo-600" to={`/deals/${dealId}/review`}>Check supporting figures →</Link></div>{review.error && <p role="alert" className="mt-3 text-sm text-rose-700">{review.error.message}</p>}</section> : <>
      {activeTab === "cim" && <CimView memo={latestOf("cim")} onCite={setCitationBlockId} />}
      {activeTab === "teaser" && <TeaserView memo={latestOf("teaser")} />}
      {activeTab === "proforma" && <ProformaView memo={latestOf("proforma")} />}
      </>}

      <CitationDrawer dealId={dealId} blockId={citationBlockId} onClose={() => setCitationBlockId(null)} />
    </div>
  );
}

// --- CIM --------------------------------------------------------------

function CimView({
  memo,
  onCite,
}: {
  memo: MemoVersion | undefined;
  onCite: (blockId: string) => void;
}) {
  if (!memo) return null;

  const data = memo.structured_data as unknown as CimStructuredData;

  return (
    <div className="flex flex-col gap-4">
      <DocHeader memo={memo} />

      {data.narrative && (
        <p className="rounded-lg border border-slate-200 bg-white p-4 text-sm italic text-slate-700 shadow-sm">
          {data.narrative}
        </p>
      )}

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {Object.values(data.financials).map((field) => (
          <div key={field.label} onClick={() => field.source_block_id && onCite(field.source_block_id)}>
            <StatTile field={field} />
          </div>
        ))}
      </div>

      {data.cross_check_flags.length > 0 && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
          <p className="mb-1 font-medium">Reviewer notes / cross-check flags</p>
          <ul className="list-inside list-disc space-y-0.5">
            {data.cross_check_flags.map((f, i) => (
              <li key={i}>{f}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
        <h3 className="mb-2 text-sm font-semibold text-slate-800">Cap Table</h3>
        {data.cap_table.available ? (
          <table className="w-full text-sm">
            <tbody>
              {data.cap_table.rows.map((row, i) => (
                <tr key={i} className="border-t border-slate-100 first:border-t-0">
                  <td className="py-1 text-slate-800">{row.holder ?? "—"}</td>
                  <td className="py-1 text-slate-800">{row.pct !== null ? `${row.pct}%` : "—"}</td>
                  <td className="py-1 text-slate-500">{row.share_class ?? "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <p className="text-sm text-slate-500">Not available or not disclosed for this deal.</p>
        )}
      </div>

      <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
        <h3 className="mb-2 text-sm font-semibold text-slate-800">Funding History</h3>
        {data.funding_history.available ? (
          <table className="w-full text-sm">
            <tbody>
              {data.funding_history.rounds.map((r, i) => (
                <tr key={i} className="border-t border-slate-100 first:border-t-0">
                  <td className="py-1 text-slate-800">{r.round_name ?? "—"}</td>
                  <td className="py-1 text-slate-800">
                    {r.amount !== null ? `$${r.amount.toLocaleString()}` : "—"}
                  </td>
                  <td className="py-1 text-slate-500">{r.date ?? "—"}</td>
                  <td className="py-1 text-slate-500">{r.lead_investor ?? "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <p className="text-sm text-slate-500">No approved funding history for this deal.</p>
        )}
      </div>

      {data.external_signals.length > 0 && (
        <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
          <h3 className="mb-2 text-sm font-semibold text-slate-800">External Signals</h3>
          <p className="mb-2 text-xs text-slate-500">
            Supporting context, not independent verification of the figures above.
          </p>
          <ul className="space-y-1 text-sm text-slate-700">
            {data.external_signals.map((sig, i) => (
              <li key={i}>
                <span className="font-medium">[{sig.topic}]</span> {sig.content}
              </li>
            ))}
          </ul>
        </div>
      )}

      {data.charts.length > 0 && (
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          {data.charts.map((chart, i) => (
            <img
              key={i}
              src={`/${chart.storage_uri}`}
              alt={chart.chart_type}
              className="rounded-lg border border-slate-200 bg-white p-2 shadow-sm"
            />
          ))}
        </div>
      )}
    </div>
  );
}

// --- Teaser --------------------------------------------------------------

function TeaserView({ memo }: { memo: MemoVersion | undefined }) {
  if (!memo) return null;

  const data = memo.structured_data as unknown as TeaserStructuredData;

  return (
    <div className="flex flex-col gap-4">
      <DocHeader memo={memo} />

      <p className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Historical approval fields do not establish current release or permission to send externally.</p>
      <p className="rounded-lg border border-slate-200 bg-white p-4 text-sm text-slate-800 shadow-sm">
        {data.business_description}
      </p>

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {Object.values(data.financials).map((field) => (
          <StatTile key={field.label} field={field} />
        ))}
      </div>

      {data.charts.length > 0 && (
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          {data.charts.map((chart, i) => (
            <img
              key={i}
              src={`/${chart.storage_uri}`}
              alt={chart.chart_type}
              className="rounded-lg border border-slate-200 bg-white p-2 shadow-sm"
            />
          ))}
        </div>
      )}

      <p className="text-xs text-slate-500">Financials and cap table may be missing or unverified. Check the current room and source documents.</p>
    </div>
  );
}

// --- Pro-forma ---------------------------------------------------------

function ProformaView({ memo }: { memo: MemoVersion | undefined }) {
  if (!memo) return null;

  const data = memo.structured_data as unknown as ProformaStructuredData;

  return (
    <div className="flex flex-col gap-4">
      <DocHeader memo={memo} />

      <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-800">
        <p className="font-medium">PROJECTED, NOT EXTRACTED</p>
        <p className="mt-1 text-xs">
          Every number below is computed from the stated assumptions, not sourced from a document. Never
          treat it at the same confidence tier as the CIM's cited figures.
        </p>
      </div>

      <div className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
        <h3 className="mb-2 text-sm font-semibold text-slate-800">Assumptions</h3>
        <ul className="list-inside list-disc space-y-1 text-sm text-slate-700">
          {data.assumptions.map((a, i) => (
            <li key={i} className={a.startsWith("WARNING") ? "text-rose-700" : undefined}>
              {a}
            </li>
          ))}
        </ul>
      </div>

      <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white shadow-sm">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left text-xs text-slate-500">
              <th className="px-3 py-2 font-medium">Year</th>
              <th className="px-3 py-2 font-medium">Projected ARR</th>
              <th className="px-3 py-2 font-medium">Projected Cash on Hand</th>
            </tr>
          </thead>
          <tbody>
            {data.rows.map((row) => (
              <tr key={row.year} className="border-t border-slate-100">
                <td className="px-3 py-2 text-slate-800">Year {row.year}</td>
                <td className="px-3 py-2 text-slate-800">{formatFieldValue(row.arr, "USD")}</td>
                <td className="px-3 py-2 text-slate-800">
                  {row.cash_on_hand !== null ? formatFieldValue(row.cash_on_hand, "USD") : "not projected"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// --- Shared --------------------------------------------------------------

function DocHeader({
  memo,
}: {
  memo: MemoVersion;
}) {
  return (
    <div className="flex items-center justify-between text-xs text-slate-500">
      <span>
        v{memo.version_number} · generated {new Date(memo.generated_at).toLocaleString()}
      </span>
    </div>
  );
}
