import {Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {useDeals,useLeads} from '../api/hooks';
import {api} from '../api/client';
import type {InvestmentCaseData} from '../components/InvestmentCase';
type Work={id:string;lead_id:string;basis_hash:string;investment_case?:InvestmentCaseData;automation?:{status:string;phase:string}};
export default function Dashboard(){
 const leads=useLeads();const deals=useDeals();
 const work=useQuery({queryKey:['operations'],queryFn:()=>api.get<Work[]>('/api/operations/workspaces'),refetchInterval:q=>q.state.data?.some(w=>['queued','running'].includes(w.automation?.status||''))?2000:false});
 const companies=leads.data?.filter(l=>l.company_profile && ['reviewed','promoted_to_deal'].includes(l.status))||[];
 const linked=new Set(leads.data?.map(l=>l.promoted_deal_id).filter(Boolean));
 const standalone=deals.data?.filter(d=>!linked.has(d.deal.id))||[];
 if(leads.isLoading||work.isLoading)return <p>Loading company work…</p>;
 if(leads.error||work.error)return <p role="alert">{(leads.error||work.error)?.message}</p>;
 return <div className="space-y-7"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">Move companies toward a fundraise</h1><p className="mt-3 text-slate-500">Decide where to spend effort. Prepare the work. Resolve what holds the company back.</p></div><Link className="rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white" to="/leads">Find companies →</Link></header>
 <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Company work</h2>{!companies.length && <p className="mt-4 text-sm text-slate-500">Shortlist companies in Discover. AI preparation starts from their sourced evidence.</p>}<div className="mt-3 divide-y divide-slate-100">{companies.map(l=>{const w=work.data?.find(w=>w.lead_id===l.id);const c=w?.investment_case?.version===8 && w?.investment_case?.basis_hash===w?.basis_hash?w?.investment_case:undefined;const running=['queued','running'].includes(w?.automation?.status||'');const missing=Object.values(c?.products||{}).flatMap(p=>p.missing_inputs);const label=running?w?.automation?.phase:c?.status==='needs_review'?'Drafts need further checking':c?.fit?.decision==='do_not_pursue'?'Engagement mismatch':c?.fit?.decision==='clarify'?'Fit needs clarification':missing.length?'Company inputs needed':c?.status==='complete'?'Preparation drafts available':'Investment case not prepared';return <article className="flex flex-wrap items-start justify-between gap-5 py-6" key={l.id}><div className="min-w-0 flex-1"><Link className="text-lg font-semibold hover:text-indigo-600" to={`/operations?lead=${l.id}`}>{l.company_name}</Link><p className="mt-2 text-sm font-medium text-indigo-700">{label}</p><p className="mt-2 max-w-3xl line-clamp-3 text-sm leading-6 text-slate-600">{c?.fit?.rationale||l.company_profile?.evidence.find(e=>e.field==='offering')?.value||'Company evidence needs research.'}</p>{missing[0] && <p className="mt-3 text-sm text-amber-800">Needed next: {missing[0].record}</p>}</div><Link className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-indigo-600" to={`/operations?lead=${l.id}&tab=readiness`}>{c?.fit?'Open decision & work →':'Prepare investment case →'}</Link></article>})}</div></section>
 <details className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer text-sm font-medium text-slate-500">Standalone document records ({standalone.length})</summary><p className="mt-3 text-sm text-slate-500">Documents created outside the company workflow. Compilation status is a document-processing state.</p>{deals.error && <p role="alert">{deals.error.message}</p>}<ul className="mt-4 space-y-3">{standalone.map(d=><li key={d.deal.id}><Link className="text-sm text-indigo-600" to={`/deals/${d.deal.id}/documents`}>{d.deal.name} →</Link></li>)}</ul></details>
 </div>
}
