const modulePath=process.env.DISCOVERY_PLAYWRIGHT_MODULE || 'playwright';
const {chromium}=require(modulePath);const {expect}=require(modulePath+'/test');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1360,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const lead={id:'selected',company_name:'Fixture Company',status:'promoted_to_deal',promoted_deal_id:'deal',company_profile:{name:'Fixture Company',website:'https://example.test',evidence:[{id:'offering',field:'offering',value:'Manufactures industrial parts',quote:'Manufactures industrial parts',source_url:'https://example.test'}]}};
const w={id:'workspace',lead_id:'selected',revision:1,basis_hash:'first',company_brief:{},metrics:{months:[],calculations:[],missing:[],note:'Company-reported figures, not independently verified.'},controls:[],events:[]};let saved,imported;
await page.route('http://localhost:5173/api/**',async route=>{const path=new URL(route.request().url()).pathname;let body;
if(path==='/api/leads')body=[lead];else if(path==='/api/operations/workspaces')body=[w];else if(path==='/api/deals/deal')body={id:'deal',name:lead.company_name,status:'new',document_ids:[]};else if(path==='/api/deals/deal/review')body={extraction_result:null,cross_check_flags:[],ready_for_compilation:false};else if(path==='/api/deals/deal/source-documents')body=[];
else if(path==='/api/operations/workspaces/workspace/metrics' && route.request().method()==='POST'){saved=route.request().postDataJSON();w.revision++;w.metrics.months=[{id:'m1',...saved.update}];body=w;}
else if(path==='/api/operations/workspaces/workspace/metric-imports'){imported=route.request().postDataJSON();w.revision++;w.metric_imports=[{id:'import1',source_name:imported.source_name,status:'queued',issues:[]}];w.automation={status:'queued',phase:'Reading company update'};body=w;}
else throw Error('Unexpected '+path);
await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});});
await page.goto('http://localhost:5173/deals/deal/review');await expect(page.getByRole('heading',{name:'Check figures from company documents'})).toBeVisible();await expect(page.getByRole('button',{name:'Add document',exact:true})).toBeDisabled();await expect(page.getByText(/directive bar above/)).toHaveCount(0);await expect(page.getByText(/Directive, or leave/)).not.toBeVisible();
await page.getByRole('link',{name:'Back to company research, metrics & pitch →'}).click();await expect(page.getByRole('heading',{name:'Business performance'})).toBeVisible();await page.getByRole('button',{name:'Enter figures manually',exact:true}).click();await page.getByLabel('Completed month',{exact:true}).fill('2025-02');await page.getByLabel('Currency',{exact:true}).fill('INR');await page.getByLabel('Recognized revenue',{exact:true}).fill('150');await page.getByLabel('Direct variable delivery costs',{exact:true}).fill('180');await page.getByLabel('Source and definition',{exact:true}).fill('Finance report for February; recognized company fees and direct delivery costs.');await page.getByRole('button',{name:'Save & calculate',exact:true}).click();await expect(page.getByRole('link',{name:'Download metrics ↓'})).toBeVisible();assert.equal(saved.expected_revision,1);assert.equal(saved.update.revenue,'150');assert.equal(saved.update.paying_customers,null);assert.equal(saved.update.cash,null);await expect(page.getByText('150',{exact:true})).toBeVisible();
await page.getByLabel('Update source',{exact:true}).fill('Founder January update');await page.getByLabel('Company update',{exact:true}).fill('January 2025 actuals in INR. Recognized revenue: 100000.');await page.getByRole('button',{name:'Read update & update analysis',exact:true}).click();await expect(page.getByText('Update queued for AI extraction.',{exact:true})).toBeVisible();assert.equal(imported.expected_revision,2);assert(imported.text.includes('100000'));await expect(page.getByRole('button',{name:'Company work in progress…',exact:true})).toBeDisabled();w.automation={status:'completed',phase:'Saved'};w.metric_imports[0]={...w.metric_imports[0],status:'applied',record_ids:['m2'],issues:['Cash was not stated.']};await page.reload();await expect(page.getByText('Cash was not stated.',{exact:true})).toBeVisible();
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS document-review purpose/empty state, company return link, monthly figures form, unknown preservation, source note, AI update submission, polling, exceptions and mobile metrics');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
